/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
'use client';
import { useEffect, useState } from 'react';
import { BadgeIndianRupee, Building2, QrCode, Upload, ShieldCheck } from 'lucide-react';
import { PageContainer } from '@/components/layout/PageContainer';
import { FinancialPageHeader } from '@/components/features/financial/FinancialPageHeader';
import { Button, Card, Input, Select, StatusBadge, Table, useToast } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { merchantPaymentService, TopUpMode, TopUpRequest } from '@/services/merchantPaymentService';
import { formatCurrency, formatDateTime } from '@/utils/formatters';

export default function TopUpPage() {
  const { session } = useAuth(); const { toastSuccess, toastError } = useToast();
  const retailerId = session?.entityId || 'RET001'; const [items, setItems] = useState<TopUpRequest[]>([]);
  const [amount, setAmount] = useState(''); const [mode, setMode] = useState<TopUpMode>('BANK_TRANSFER'); const [reference, setReference] = useState(''); const [remarks, setRemarks] = useState(''); const [proof, setProof] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => setItems(merchantPaymentService.getTopUps(retailerId));
  useEffect(() => { load(); const fn = () => load(); window.addEventListener('qinstar_fintech_updated', fn); return () => window.removeEventListener('qinstar_fintech_updated', fn); }, [retailerId]);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const value = Number(amount); if (!Number.isFinite(value) || value < 100) return toastError('Minimum top-up request is â‚¹100.'); if (!reference.trim()) return toastError('Enter the bank UTR or UPI reference.'); setBusy(true); await merchantPaymentService.createTopUp({ retailerId, retailerName: session?.name || 'Metro Store #01', walletId: 'wlt_ret_001', amount: value, mode, reference: reference.trim(), remarks: remarks.trim() || 'Retailer wallet top-up', proofName: proof || undefined }); setAmount(''); setReference(''); setRemarks(''); setProof(''); load(); setBusy(false); toastSuccess('Top-up request sent for admin approval.'); };
  const cols: any[] = [{ key:'id', header:'Request ID', render:(r:TopUpRequest)=><span className="font-mono font-semibold text-[#0F4C81]">{r.id}</span> }, { key:'createdAt', header:'Requested', render:(r:TopUpRequest)=>formatDateTime(r.createdAt) }, { key:'mode', header:'Mode' }, { key:'reference', header:'UTR / Reference' }, { key:'amount', header:'Amount', align:'right', render:(r:TopUpRequest)=><b>{formatCurrency(r.amount)}</b> }, { key:'status', header:'Status', render:(r:TopUpRequest)=><StatusBadge status={r.status} /> }];
  return <PageContainer><div className="space-y-6 max-w-7xl mx-auto"><FinancialPageHeader title="Wallet Top-Up Request" subtitle="Submit funded bank, UPI or QR transfers for maker-checker approval before wallet credit." statusBadge={<StatusBadge status="ACTIVE" label="Admin controlled" />} />
    <div className="grid lg:grid-cols-[1.05fr_.95fr] gap-5"><Card title="Create top-up request" subtitle="Wallet balance changes only after admin approval."><form onSubmit={submit} className="grid sm:grid-cols-2 gap-4"><Input label="Amount" required type="number" min="100" value={amount} onChange={e=>setAmount(e.target.value)} leftIcon={<BadgeIndianRupee className="w-4 h-4" />} /><Select label="Payment mode" required value={mode} onChange={e=>setMode(e.target.value as TopUpMode)} options={[{value:'BANK_TRANSFER',label:'Bank transfer (NEFT/IMPS/RTGS)'},{value:'UPI',label:'UPI transfer'},{value:'QR',label:'QR payment'}]} /><Input label="UTR / transaction reference" required value={reference} onChange={e=>setReference(e.target.value)} /><Input label="Remarks" value={remarks} onChange={e=>setRemarks(e.target.value)} /><label className="sm:col-span-2 text-xs font-semibold text-slate-700">Payment proof (PDF/JPG/PNG)<span className="mt-1 flex h-20 items-center justify-center gap-2 rounded-lg border border-dashed border-slate-300 bg-slate-50 cursor-pointer"><Upload className="w-4 h-4" />{proof || 'Choose receipt'}<input className="hidden" type="file" accept=".pdf,image/*" onChange={e=>setProof(e.target.files?.[0]?.name || '')} /></span></label><Button type="submit" isLoading={busy} className="sm:col-span-2">Send for approval</Button></form></Card>
    <Card title="Settlement account" subtitle="Transfer first, then submit the successful transaction reference."><div className="space-y-4 text-sm"><div className="p-4 bg-blue-50 border border-blue-200 rounded-xl flex gap-3"><Building2 className="w-5 h-5 text-[#0F4C81]" /><div><b>Qin Star Payment Technologies Pvt Ltd</b><p className="text-slate-600 mt-1 font-mono">Axis Bank Â· A/C 925020013768300 Â· IFSC UTIB0001134</p></div></div><div className="p-4 bg-amber-50 border border-amber-200 rounded-xl flex gap-3"><ShieldCheck className="w-5 h-5 text-amber-700" /><p>Requests are screened for duplicate UTRs and reconciled against the bank statement. Approval creates a wallet ledger credit using the request ID.</p></div><div className="flex items-center gap-2 text-slate-600"><QrCode className="w-4 h-4" /> QR transfers are supported through the same approval process.</div></div></Card></div>
    <Card title="Top-up history" noPadding><Table columns={cols} data={items} keyExtractor={r=>r.id} emptyTitle="No top-up requests" emptyDescription="Your submitted requests will appear here." /></Card></div></PageContainer>;
}

