/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
'use client';
import { useMemo, useState } from 'react';
import { Download, Info, RefreshCw } from 'lucide-react';
import { PageContainer } from '@/components/layout/PageContainer';
import { FinancialPageHeader } from '@/components/features/financial/FinancialPageHeader';
import { Button, Card, Input, StatusBadge, Table } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { merchantPaymentService } from '@/services/merchantPaymentService';
import { reportService } from '@/services/reportService';
import { formatCurrency, formatDateTime } from '@/utils/formatters';

export default function UnsettledReportPage(){const {session}=useAuth();const retailerId=session?.entityId||'RET001';const all=merchantPaymentService.getUnsettled(retailerId);const [from,setFrom]=useState('2026-09-01');const [to,setTo]=useState('2026-09-30');const [refresh,setRefresh]=useState(0);const rows=useMemo(()=>all.filter(r=>r.createdAt.slice(0,10)>=from&&r.createdAt.slice(0,10)<=to),[all,from,to,refresh]);const cols:any[]=[{key:'orderId',header:'Order ID',render:(r:any)=><span className="font-mono font-semibold text-[#0F4C81]">{r.orderId}</span>},{key:'service',header:'Service'},{key:'amount',header:'Gross amount',align:'right',render:(r:any)=><b>{formatCurrency(r.amount)}</b>},{key:'netAmount',header:'Expected net',align:'right',render:(r:any)=>formatCurrency(r.netAmount)},{key:'createdAt',header:'Txn date',render:(r:any)=>formatDateTime(r.createdAt)},{key:'settlementDate',header:'Expected T+1',render:(r:any)=>formatDateTime(r.settlementDate)},{key:'settlementStatus',header:'Settlement',render:(r:any)=><StatusBadge status={r.settlementStatus} label={r.settlementStatus.replaceAll('_',' ')}/>},{key:'status',header:'Txn status',render:(r:any)=><StatusBadge status={r.status}/>}];return <PageContainer><div className="space-y-6"><FinancialPageHeader title="Unsettled Transactions (T+1)" subtitle="Successful collections awaiting the next eligible settlement cycle." actions={<><Button variant="outline" onClick={()=>setRefresh(v=>v+1)} leftIcon={<RefreshCw className="w-4 h-4"/>}>Refresh</Button><Button onClick={()=>reportService.exportToCsv('unsettled-t1',rows)} leftIcon={<Download className="w-4 h-4"/>}>Export CSV</Button></>}/><div className="grid sm:grid-cols-3 gap-4"><Card><p className="text-xs text-slate-500">Unsettled transactions</p><b className="text-2xl">{rows.length}</b></Card><Card><p className="text-xs text-slate-500">Gross receivable</p><b className="text-2xl">{formatCurrency(rows.reduce((a,r)=>a+r.amount,0))}</b></Card><Card><p className="text-xs text-slate-500">Expected net settlement</p><b className="text-2xl text-[#0F4C81]">{formatCurrency(rows.reduce((a,r)=>a+r.netAmount,0))}</b></Card></div><Card title="Settlement window" action={<div className="flex gap-2"><Input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>} noPadding><Table columns={cols} data={rows} keyExtractor={r=>r.id}/></Card><div className="p-4 rounded-xl border border-blue-200 bg-blue-50 flex gap-3 text-xs text-slate-700"><Info className="w-5 h-5 text-[#0F4C81] shrink-0"/><p>T+1 is the expected settlement date after a successful transaction. Bank holidays, risk holds, chargebacks, reconciliation exceptions and provider cut-off times can move a transaction outside the standard cycle.</p></div></div></PageContainer>}

